name: Deploy Angular App

on:
  push:
    branches: [ master ]

permissions:
  contents: write   
  pages: write    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_BASE: /watchlist/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build -- --configuration production --base-href "${{ env.APP_BASE }}"
      - run: cp dist/watchlist/browser/index.html dist/watchlist/browser/404.html
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/watchlist/browser
